# Code Generated by Sidekick is for learning and experimentation purposes only.
import base64
import io
from pathlib import Path

import qrcode
import streamlit as st
import streamlit.components.v1 as components

# Page config
st.set_page_config(
    page_title="Sanjai & Pradhiksha",
    page_icon="💜",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# Code Generated by Sidekick is for learning and experimentation purposes only.
st.markdown(
    """
    <style>
      /* Code Generated by Sidekick is for learning and experimentation purposes only. */
      #MainMenu, footer, header, .stDeployButton { display: none !important; }

      /* Remove Streamlit padding and make background match invite */
      .block-container { padding: 0 !important; max-width: 100% !important; }
      [data-testid="stAppViewContainer"] { background: #0d0a12 !important; }

      /* Make iframe blend in */
      iframe { border: 0 !important; width: 100% !important; display: block; }
    </style>
    """,
    unsafe_allow_html=True,
)


# ---- Settings (edit these) ----
LOCATION_URL = "https://maps.app.goo.gl/P3wjeL2VR1PcUjFC9"
WEDDING_ISO = "2026-05-17T18:00:00+05:30"  # IST target time
TEMPLATE_PATH = Path(__file__).parent / "invite_template.html"

# ---- QR generation (base64 for embedding in HTML) ----
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=2,
)
qr.add_data(LOCATION_URL)
qr.make(fit=True)
img = qr.make_image(fill_color="black", back_color="white").convert("RGB")

buf = io.BytesIO()
img.save(buf, format="PNG")
qr_b64 = base64.b64encode(buf.getvalue()).decode("utf-8")

# ---- Load template and inject values ----
template = TEMPLATE_PATH.read_text(encoding="utf-8")

html = (
    template.replace("{{LOCATION_URL}}", LOCATION_URL)
    .replace("{{WEDDING_ISO}}", WEDDING_ISO)
    .replace("{{QR_BASE64}}", qr_b64)
)

# ---- Render (JS runs reliably inside components.html) ----
components.html(html, height=2000, scrolling=False)
